
SIRDsims-mcmc-script.RData: SIRDsims.RData SIRDsims-mcmc-script.R
  R CMD BATCH SIRDsims-mcmc-script.R
  git pull origin master
  git add SIRDsims-mcmc-script.RData
  git commit -m "updated SIRDsims-mcmc-script.RData"
  git push

SIRDsims.RData: SIRDsims.R
  R CMD BATCH SIRDsims.R
  git pull origin master
  git add SIRDsims.RData
  git commit -m "updated SIRDsims.RData"
  git push


